export const COLOURS = {
  white: '#ffffff',
  black: '#000000',
  green: '#00AC76',
  red: '#C04345',
  blue: '#0043F9',
  backgroundLight: '#F0F0F3',
  backgroundMedium: '#B9B9B9',
  backgroundDark: '#777777',
};

export const Items = [
  {
    id: 1,
    category: 'product',
    productName: 'MI Super Bass Bluetooth Wireless Headphones',
    productPrice: 1799,
    quantity: 10,
    quantityToken:1,
    description:
      'Up to 20 hours battery life | Super powerful Bass | 40mm dynamic driver | Pressure less ear muffs | Bluetooth 5.0 | Voice control',
    arabeDescription: 'عمر بطارية يصل إلى 20 ساعة | صوت جهير فائق القوة | محرك ديناميكي 40 مم | غطاء للأذن ضغط أقل | بلوتوث 5.0 | التحكم الصوتي.',
    isOff: true,
    offPercentage: 12,
    productImage: require('../database/images/products/Mi1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/products/Mi1.png'),
      require('../database/images/products/Mi2.png'),
      require('../database/images/products/Mi3.png'),
    ],
  },
  
  {
    id: 2,
    category: 'product',
    productName: 'boAt Rockerz 450 Bluetooth Headphone',
    productPrice: 1499,
    quantity: 20,
    quantityToken:1,
    description:
      'boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
    arabeDescription: 'boAt Rockerz 450 M هي سماعة رأس لاسلكية على الأذن تم تصميمها هندسيًا لتلبية احتياجات عشاق الموسيقى.',
    isOff: true,
    offPercentage: 12,
    productImage: require('../database/images/products/boat1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/products/boat1.png'),
      require('../database/images/products/boat2.png'),
      require('../database/images/products/boat3.png'),
    ],
  },
  {
    id: 3,
    category: 'accessory',
    productName: 'boAt Airdopes 441',
    productPrice: 1999,
    quantity: 30,
    quantityToken:1,
    description:
      'Bluetooth: It has Bluetooth v5.0 with a range of 10m and is compatible with Android & iOS',
    arabeDescription: 'البلوتوث: يحتوي على بلوتوث v5.0 بمدى يصل إلى 10 أمتار ومتوافق مع Android و iOS',
    isOff: true,
    offPercentage: 20,
    productImage: require('../database/images/accessories/boatairpods1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boatairpods1.png'),
      require('../database/images/accessories/boatairpods2.png'),
      require('../database/images/accessories/boatairpods3.png'),
    ],
  },
  {
    id: 4,
    category: 'accessory',
    productName: 'boAt Bassheads 242',
    productPrice: 399,
    quantity: 40,
    quantityToken:1,
    description:
      'Fly into your workouts with precise tones that inspire and energize your system with its HD sound, all the time.',
    arabeDescription: 'انتقل إلى التدريبات الخاصة بك بنغمات دقيقة تلهم نظامك وتنشطه بصوت عالي الدقة ، طوال الوقت.',
    isOff: false,
    productImage: require('../database/images/accessories/boatbassheads1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boatbassheads1.png'),
      require('../database/images/accessories/boatbassheads2.png'),
      require('../database/images/accessories/boatbassheads3.png'),
    ],
  },
  {
    id: 5,
    category: 'accessory',
    productName: 'boAt Rockerz 255 Pro+',
    productPrice: 1499,
    quantity: 50,
    quantityToken:1,
    description:
      'The unbeatable boAt signature sound shines through no matter what are you playing courtesy its 10mm drivers.',
    arabeDescription: 'يتألق صوت BoAt المميز الذي لا يهزم بغض النظر عن ما تلعبه بفضل محركاتها مقاس 10 مم.',
    isOff: false,
    productImage: require('../database/images/accessories/boatrockerz1.png'),
    isAvailable: false,
    productImageList: [
      require('../database/images/accessories/boatrockerz1.png'),
      require('../database/images/accessories/boatrockerz2.png'),
      require('../database/images/accessories/boatrockerz3.png'),
    ],
  },
  {
    id: 6,
    category: 'accessory',
    productName: 'Boult Audio AirBass Propods TWS',
    productPrice: 1299,
    quantity: 60,
    quantityToken:1,
    description:
      'One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant',
    arabeDescription: 'التحكم بلمسة واحدة ومساعد الصوت: مع زر واحد متعدد الوظائف ، يمكنك تشغيل / إيقاف مؤقت ، المسار السابق / التالي والإجابة / إنهاء المكالمات. تتيح لك وظيفة المساعد الصوتي الوصول إلى مساعد siri / Google',
    isOff: true,
    offPercentage: 20,
    productImage: require('../database/images/accessories/boultairbass1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boultairbass1.png'),
      require('../database/images/accessories/boultairbass2.png'),
      require('../database/images/accessories/boultairbass3.png'),
    ],
  },
  {
    id: 7,
    category: 'product',
    productName: 'boAt Rockerz 450 Bluetooth Headphone',
    productPrice: 1499,
    quantity: 5,
    quantityToken:1,
    description:
      'boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
    arabeDescription: 'boAt Rockerz 450 M هي سماعة رأس لاسلكية على الأذن تم تصميمها هندسيًا لتلبية احتياجات عشاق الموسيقى.',
    isOff: false,
    productImage: require('../database/images/products/boat1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/products/boat1.png'),
      require('../database/images/products/boat2.png'),
      require('../database/images/products/boat3.png'),
    ],
  },
  {
    id: 8,
    category: 'product',
    productName: 'boAt Rockerz 450 Bluetooth Headphone',
    productPrice: 1499,
    quantity: 70,
    quantityToken:1,
    description:
      'boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
    arabeDescription: 'boAt Rockerz 450 M هي سماعة رأس لاسلكية على الأذن تم تصميمها هندسيًا لتلبية احتياجات عشاق الموسيقى.',
    isOff: false,
    productImage: require('../database/images/products/boat1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/products/boat1.png'),
      require('../database/images/products/boat2.png'),
      require('../database/images/products/boat3.png'),
    ],
  },
  {
    id: 9,
    category: 'product',
    productName: 'boAt Rockerz 450 Bluetooth Headphone',
    productPrice: 1499,
    quantity: 80,
    quantityToken:1,
    description:
      'boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
    arabeDescription: 'boAt Rockerz 450 M هي سماعة رأس لاسلكية على الأذن تم تصميمها هندسيًا لتلبية احتياجات عشاق الموسيقى.',
    isOff: false,
    productImage: require('../database/images/products/boat1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/products/boat1.png'),
      require('../database/images/products/boat2.png'),
      require('../database/images/products/boat3.png'),
    ],
  },
  {
    id: 10,
    category: 'product',
    productName: 'boAt Rockerz 450 Bluetooth Headphone',
    productPrice: 1499,
    quantity: 45,
    quantityToken:1,
    description:
      'boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
    arabeDescription: 'boAt Rockerz 450 M هي سماعة رأس لاسلكية على الأذن تم تصميمها هندسيًا لتلبية احتياجات عشاق الموسيقى.',
    isOff: false,
    productImage: require('../database/images/products/boat1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/products/boat1.png'),
      require('../database/images/products/boat2.png'),
      require('../database/images/products/boat3.png'),
    ],
  },
  {
    id:11,
    category: 'product',
    productName: 'boAt Rockerz 450 Bluetooth Headphone',
    productPrice: 1499,
    quantity: 55,
    quantityToken:1,
    description:
      'boAt Rockerz 450 M is an on-ear wireless headset that has been ergonomically designed to meet the needs of music lovers.',
    arabeDescription: 'boAt Rockerz 450 M هي سماعة رأس لاسلكية على الأذن تم تصميمها هندسيًا لتلبية احتياجات عشاق الموسيقى.',
    isOff: false,
    productImage: require('../database/images/products/boat1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/products/boat1.png'),
      require('../database/images/products/boat2.png'),
      require('../database/images/products/boat3.png'),
    ],
  },
  {
    id: 12,
    category: 'accessory',
    productName: 'boAt Airdopes 441',
    productPrice: 1999,
    quantity: 65,
    quantityToken:1,
    description:
      'Bluetooth: It has Bluetooth v5.0 with a range of 10m and is compatible with Android & iOS',
    arabeDescription: 'البلوتوث: يحتوي على بلوتوث v5.0 بمدى يصل إلى 10 أمتار ومتوافق مع Android و iOS',
    isOff: true,
    offPercentage: 20,
    productImage: require('../database/images/accessories/boatairpods1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boatairpods1.png'),
      require('../database/images/accessories/boatairpods2.png'),
      require('../database/images/accessories/boatairpods3.png'),
    ],
  },
  {
    id: 13,
    category: 'accessory',
    productName: 'boAt Bassheads 242',
    productPrice: 399,
    quantity: 75,
    quantityToken:1,
    description:
      'Fly into your workouts with precise tones that inspire and energize your system with its HD sound, all the time.',
    arabeDescription: 'انتقل إلى التدريبات الخاصة بك بنغمات دقيقة تلهم نظامك وتنشطه بصوت عالي الدقة ، طوال الوقت.',
    isOff: false,
    productImage: require('../database/images/accessories/boatbassheads1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boatbassheads1.png'),
      require('../database/images/accessories/boatbassheads2.png'),
      require('../database/images/accessories/boatbassheads3.png'),
    ],
  },
  {
    id: 14,
    category: 'accessory',
    productName: 'boAt Rockerz 255 Pro+',
    productPrice: 1499,
    quantity: 85,
    quantityToken:1,
    description:
      'The unbeatable boAt signature sound shines through no matter what are you playing courtesy its 10mm drivers.',
    arabeDescription: 'يتألق صوت BoAt المميز الذي لا يهزم بغض النظر عن ما تلعبه بفضل محركاتها مقاس 10 مم.',
    isOff: false,
    productImage: require('../database/images/accessories/boatrockerz1.png'),
    isAvailable: false,
    productImageList: [
      require('../database/images/accessories/boatrockerz1.png'),
      require('../database/images/accessories/boatrockerz2.png'),
      require('../database/images/accessories/boatrockerz3.png'),
    ],
  },
  {
    id: 15,
    category: 'accessory',
    productName: 'Boult Audio AirBass Propods TWS',
    productPrice: 1299,
    quantity: 95,
    quantityToken:1,
    description:
      'One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant',
    arabeDescription: 'التحكم بلمسة واحدة ومساعد الصوت: مع زر واحد متعدد الوظائف ، يمكنك تشغيل / إيقاف مؤقت ، المسار السابق / التالي والإجابة / إنهاء المكالمات. تتيح لك وظيفة المساعد الصوتي الوصول إلى مساعد siri / Google',
    isOff: true,
    offPercentage: 20,
    productImage: require('../database/images/accessories/boultairbass1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boultairbass1.png'),
      require('../database/images/accessories/boultairbass2.png'),
      require('../database/images/accessories/boultairbass3.png'),
    ],
  },
  {
    id: 16,
    category: 'accessory',
    productName: 'boAt Airdopes 441',
    productPrice: 1999,
    quantity: 15,
    quantityToken:1,
    description:
      'Bluetooth: It has Bluetooth v5.0 with a range of 10m and is compatible with Android & iOS',
    arabeDescription: 'لبلوتوث: يحتوي على بلوتوث v5.0 بمدى يصل إلى 10 أمتار ومتوافق مع Android و iOS',
    isOff: true,
    offPercentage: 20,
    productImage: require('../database/images/accessories/boatairpods1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boatairpods1.png'),
      require('../database/images/accessories/boatairpods2.png'),
      require('../database/images/accessories/boatairpods3.png'),
    ],
  },
  {
    id: 17,
    category: 'accessory',
    productName: 'boAt Bassheads 242',
    productPrice: 399,
    quantity: 25,
    quantityToken:1,
    description:
      'Fly into your workouts with precise tones that inspire and energize your system with its HD sound, all the time.',
    arabeDescription: 'انتقل إلى التدريبات الخاصة بك بنغمات دقيقة تلهم نظامك وتنشطه بصوت عالي الدقة ، طوال الوقت.',
    isOff: false,
    productImage: require('../database/images/accessories/boatbassheads1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boatbassheads1.png'),
      require('../database/images/accessories/boatbassheads2.png'),
      require('../database/images/accessories/boatbassheads3.png'),
    ],
  },
  {
    id: 18,
    category: 'accessory',
    productName: 'boAt Rockerz 255 Pro+',
    productPrice: 1499,
    quantity: 35,
    quantityToken:1,
    description:
      'The unbeatable boAt signature sound shines through no matter what are you playing courtesy its 10mm drivers.',
    arabeDescription: 'يتألق صوت BoAt المميز الذي لا يهزم بغض النظر عن ما تلعبه بفضل محركاتها مقاس 10 مم.',
    isOff: false,
    productImage: require('../database/images/accessories/boatrockerz1.png'),
    isAvailable: false,
    productImageList: [
      require('../database/images/accessories/boatrockerz1.png'),
      require('../database/images/accessories/boatrockerz2.png'),
      require('../database/images/accessories/boatrockerz3.png'),
    ],
  },
  {
    id: 19,
    category: 'accessory',
    productName: 'Boult Audio AirBass Propods TWS',
    productPrice: 1299,
    quantity: 5,
    quantityToken:1,
    description:
      'One Touch Control & Voice Assistant: With one multifunction button, you can play/pause, previous/next track and answer/hang-up calls.Voice assistant function lets you access siri/Google Assistant',
    arabeDescription: 'التحكم بلمسة واحدة ومساعد الصوت: مع زر واحد متعدد الوظائف ، يمكنك تشغيل / إيقاف مؤقت ، المسار السابق / التالي والإجابة / إنهاء المكالمات. تتيح لك وظيفة المساعد الصوتي الوصول إلى مساعد siri / Google',
    isOff: true,
    offPercentage: 20,
    productImage: require('../database/images/accessories/boultairbass1.png'),
    isAvailable: true,
    productImageList: [
      require('../database/images/accessories/boultairbass1.png'),
      require('../database/images/accessories/boultairbass2.png'),
      require('../database/images/accessories/boultairbass3.png'),
    ],
  },
];
